package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComSileniumDevComposeAvRefsHeadsMain'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComSileniumDevComposeAvRefsHeadsMain")
    name = "https://github.com/silenium-dev/compose-av#refs/heads/main"
    url = "https://github.com/silenium-dev/compose-av"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "silenium-dev"
        password = "credentialsJSON:92f54d4a-4857-4b28-91da-6d34259d0871"
    }
}))

