name: Setup native build environment
inputs:
  ffmpeg-platform:
    description: 'The platform to fetch the native libraries for'
    default: 'linux-x86_64'
  ffmpeg-version:
    description: 'The version of the native libraries to fetch'
    default: '7.0+0.1.0'
runs:
  using: composite
  steps:
    - name: Install environment
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libva-dev libdrm-dev libegl-dev libgl-dev libgles-dev
