name: "Build and Test"
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
  release:
    types: [ published ]
permissions:
  pull-requests: write
  contents: write
jobs:
  build-publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 4G
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago
          purge-created: 0
          # or last accessed this duration (ISO 8601 duration format)
          # before the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: P7D
          # except any version with the key that is the same as the `primary-key`
          purge-primary-key: never
      - uses: silenium-dev/actions/kotlin@main
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          snapshot-repo-url: "https://repoflow.silenium.dev/api/maven/public/maven-snapshots"
          release-repo-url: "https://repoflow.silenium.dev/api/maven/public/maven-releases"
          repo-username: ${{ secrets.REPOFLOW_USERNAME }}
          repo-password: ${{ secrets.REPOFLOW_PASSWORD }}
          tests: false
          java-version: 17
