name: "Build and Test"
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  workflow_dispatch:
  release:
    types: [ published ]
env:
  REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
  REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
  REPOSILITE_URL: ${{ github.event_name == 'release' && 'https://reposilite.silenium.dev/releases' || 'https://reposilite.silenium.dev/snapshots' }}
permissions:
  contents: write
jobs:
  linux-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: silenium-dev/ffmpeg-static/.github/actions/deploy-ubuntu@main
        with:
          tests: true
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
      - uses: actions/upload-artifact@v4
        name: 'Upload reports'
        if: always()
        with:
          name: reports
          path: ./build/reports
          retention-days: 5
  kotlin:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: silenium-dev/ffmpeg-static/.github/actions/deploy-kotlin@main
        with:
          tests: false
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
